name: geos2
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blosc=1.21.2=hebb52c4_0
  - boost-cpp=1.78.0=h8b082ac_1
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py311h5547dcb_1005
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - cairo=1.16.0=h904041c_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py311ha86e640_3
  - cfitsio=4.2.0=hd56cc12_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.7=py311hd2070f0_0
  - cryptography=39.0.0=py311h61927ef_0
  - curl=7.87.0=h6df9250_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.6=py311h814d153_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - descartes=1.1.0=py_4
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_0
  - fiona=1.9.0=py311h9687163_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py311h5547dcb_1
  - freetype=2.12.1=h3f81eb7_1
  - freexl=1.0.6=hb7f2c08_1
  - gdal=3.6.2=py311h619941e_5
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geos=3.11.1=hf0c8a7f_0
  - geotiff=1.7.1=hd690177_6
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hbcb3906_2
  - hdf4=4.2.15=h7aa5921_5
  - hdf5=1.12.2=nompi_h48135f9_101
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - ipykernel=6.21.0=pyh736e0ef_0
  - ipython=8.9.0=pyhd1c38e8_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=hac89ed1_2
  - json-c=0.16=h01d06f9_0
  - jupyter_client=8.0.2=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py311h6eed73b_0
  - kealib=1.5.0=h5c1f988_0
  - kiwisolver=1.4.4=py311hd2070f0_1
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.14=h29502cd_1
  - lerc=4.0.0=hb486fe8_0
  - libaec=1.0.6=hf0c8a7f_1
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libcurl=7.87.0=h6df9250_0
  - libcxx=14.0.6=hccf4f1f_0
  - libdeflate=1.17=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.6.2=hcc7c896_5
  - libgfortran=5.0.0=11_3_0_h97931a8_27
  - libgfortran5=11.3.0=h082f757_27
  - libglib=2.74.1=h4c723e1_1
  - libiconv=1.17=hac89ed1_0
  - libjpeg-turbo=2.1.4=hb7f2c08_0
  - libkml=1.3.0=haeb80ef_1015
  - liblapack=3.9.0=16_osx64_openblas
  - libnetcdf=4.8.1=nompi_hc61b76e_106
  - libnghttp2=1.51.0=he2ab024_0
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpng=1.6.39=ha978bb4_0
  - libpq=15.1=h3640bf0_3
  - librttopo=1.1.0=h9461dca_12
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.0.1=hd6e941a_23
  - libsqlite=3.40.0=ha978bb4_0
  - libssh2=1.10.0=h47af595_3
  - libtiff=4.5.0=hee9004a_2
  - libwebp-base=1.2.4=h775f41a_0
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.10.3=hb9e07b5_0
  - libzip=1.9.2=h6db710c_1
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=15.0.7=h61d9ccf_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py311h5547dcb_0
  - matplotlib=3.6.3=py311h6eed73b_0
  - matplotlib-base=3.6.3=py311h2bf763f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h96cf925_1
  - networkx=3.0=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.78=ha8197d3_0
  - numpy=1.24.1=py311ha9d2c9f_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.0.7=hfd90126_2
  - packaging=23.0=pyhd8ed1ab_0
  - palettable=3.3.0=py_0
  - pandas=1.5.3=py311hd84f3f5_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311hafe3759_0
  - pip=23.0=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - plotly=5.13.0=py_0
  - plotly_express=0.4.0=py_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - poppler=23.01.0=h6e9091c_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=15.1=hbea33b9_3
  - proj=9.1.1=hf909084_2
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py311h5547dcb_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.1=py311hdc3c720_1
  - pysal=2.1.0=py_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.0=he7542f4_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyzmq=25.0.0=py311habfacb3_0
  - readline=8.1.2=h3899abd_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rtree=1.0.1=py311hbc1f44b_1
  - scikit-learn=1.2.1=py311h087fafe_0
  - scipy=1.10.0=py311h939689b_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=66.1.1=pyhd8ed1ab_0
  - shapely=2.0.1=py311h781b04c_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h225ccf5_2
  - sqlite=3.40.0=h9ae0607_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py311hd5badaa_2
  - tenacity=8.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=h8b9cbf0_0
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.2=py311h5547dcb_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzcode=2022g=hb7f2c08_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - wrapt=1.14.1=py311h5547dcb_1
  - xerces-c=3.2.4=h2007e90_1
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.12.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hbc0c0cd_6
  - pip:
    - affine==2.4.0
    - beautifulsoup4==4.11.2
    - contextily==1.2.0
    - fastjsonschema==2.16.2
    - geographiclib==2.0
    - geopy==2.3.0
    - jsonschema==4.17.3
    - libpysal==4.7.0
    - mercantile==1.2.1
    - nbformat==5.7.3
    - opencv-contrib-python==4.7.0.68
    - osmnx==1.3.0
    - pointpats==2.2.0
    - pyrsistent==0.19.3
    - rasterio==1.3.5
    - snuggs==1.4.7
    - soupsieve==2.3.2.post1
prefix: /Users/yohkawano/opt/anaconda3/envs/geos
